### ISSUE TITLE
Public Path Help

### ISSUE THREAD

**Issue by findborg** [nicklaw5/vuejs-webpack-extended#2]
I was wondering if you would help me out with something that is probably pretty simple but I am having a trick of a time to get working.
I am working in sub-directories. 
ex: localhost/et/this is where vwe is

Now everything works in dev mode but when I run the build script and copy and past the Dist folder contents to the root of the folder the image link is not working.  the url to the image is http://localhost/static/img/javascript-meme.2548e47.jpg and not to http://localhost/et/this is where vwe is/static/img/javascript-meme.2548e47.jpg

Sorry for such a simple question for you,   however,  you input would be greatly appreciated.

**Comment by findborg** [comment]
FYI,  what I want to accomplish is that the generated code can be just dropped into any directory or folder and work.

**Comment by nicklaw5** [comment]
Sounds like the build script is not pointing to the subdirectory you have chosen to work with.

Take a look at `config/index.js`. This is where the folder paths are set for the build script. You may just need to change the `assetsSubDirectory` path to point to the intended path you have chosen.

Let me know how you go.

**Comment by findborg** [comment]
I still have not gotten this to work the way I want.
Also,  Do you think that it may be a good idea to update the json for the Jade module since it is now Pug.

**Comment by findborg** [comment]
Wow,  I started all over and I think that I have got it figured out.  I will keep you posted as I work through it.
